---
azs:
- name: z1

networks:
- name: test
  type: manual
  subnets:
  - az: z1
    dns: [8.8.8.8]
    range: 10.234.0.0/16
    gateway: 10.234.0.1

vm_types:
- name: test
  network: test

compilation:
  az: z1
  workers: 3
  network: test
